### ISSUE TITLE
Is there any way to capture Jenkins post build status ?

### ISSUE THREAD

**Issue by akhil-intellect** [Mondtic/build-jenkins-job#3]
Jenkins build is success but post job have some check to decide  the job status . jenkins job is failed but action is saying job is success because build status is "success" in Jenkins but post build is failed . is there any way  to fix this ?

**Comment by Alec4r** [comment]
Thanks for the question.

Currently, you can use the param "jenkins-wait-job" in "wait" to get the build status, but the problem is if the job requires much time you will consume all the time in your GitHub actions package.

If you have an idea, we will be happy to receive your PR.
